name: "worker1"
sshKey:
  key: "./examples/gpu_worker/keys/kubecloud_rsa"
  password: ""
kubeConfig:
  path: "./kube/config"
watch:
  url: "git@gitee.com:yubing744/gitops-app-demo1.git"
  ref: "master"
  path: "/weaver.app.yaml"